### ISSUE TITLE
Installation Doubt

### ISSUE THREAD

**Issue by Charlie1093** [qqqwda/pokemeow-autoplay#17]
C:\Users\prabh\Desktop\pokemeow-autoplay-develop>py main.py "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\run_account_example.bat"
Traceback (most recent call last):
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\main.py", line 1, in <module>
    from instances.bot_instance import bot, logger, driver, catch_statistics, settings
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\instances\bot_instance.py", line 1, in <module>
    from bot import Bot
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\bot.py", line 3, in <module>
    from commands.explore import Explore
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\commands\explore.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

C:\Users\prabh\Desktop\pokemeow-autoplay-develop>pip3 install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in c:\users\prabh\appdata\local\programs\python\python311\lib\site-packages (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\prabh\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4) (2.5)

Even after doing the above i get the same issue

C:\Users\prabh\Desktop\pokemeow-autoplay-develop>set ENABLE_CHROME_HEADLESS=True

C:\Users\prabh\Desktop\pokemeow-autoplay-develop>set ENABLE_RUN_PICTURES=False

C:\Users\prabh\Desktop\pokemeow-autoplay-develop>py main.py "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\run_account_example.bat"
Traceback (most recent call last):
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\main.py", line 1, in <module>
    from instances.bot_instance import bot, logger, driver, catch_statistics, settings
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\instances\bot_instance.py", line 1, in <module>
    from bot import Bot
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\bot.py", line 3, in <module>
    from commands.explore import Explore
  File "C:\Users\prabh\Desktop\pokemeow-autoplay-develop\commands\explore.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by qqqwda** [comment]
in **run_account.bat**

replace this line

`py main.py %0`

with

`python main.py %0`
